"""remove user and conversation from querylog

Revision ID: 1586f71fdd46
Revises: 4ba03c2f7292
Create Date: 2026-05-23 15:23:11.073332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1586f71fdd46'
down_revision: Union[str, Sequence[str], None] = '4ba03c2f7292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('message_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('query_logs_user_id_fkey'), 'query_logs', type_='foreignkey')
    op.drop_constraint(op.f('query_logs_conversation_id_fkey'), 'query_logs', type_='foreignkey')
    op.create_foreign_key(None, 'query_logs', 'messages', ['message_id'], ['id'])
    op.drop_column('query_logs', 'user_id')
    op.drop_column('query_logs', 'conversation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('query_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'query_logs', type_='foreignkey')
    op.create_foreign_key(op.f('query_logs_conversation_id_fkey'), 'query_logs', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(op.f('query_logs_user_id_fkey'), 'query_logs', 'users', ['user_id'], ['id'])
    op.drop_column('query_logs', 'message_id')
    # ### end Alembic commands ###
