"""remove query from querylog

Revision ID: 1eddfdc812b0
Revises: d63c4e01939d
Create Date: 2026-05-23 16:50:38.968024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eddfdc812b0'
down_revision: Union[str, Sequence[str], None] = 'd63c4e01939d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'query')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
