"""update message model,keep query and response is same model

Revision ID: 705db0040a0d
Revises: 1586f71fdd46
Create Date: 2026-05-23 16:11:48.261080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '705db0040a0d'
down_revision: Union[str, Sequence[str], None] = '1586f71fdd46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_query', sa.Text(), nullable=False))
    op.add_column('messages', sa.Column('assistant_response', sa.Text(), nullable=False))
    op.drop_column('messages', 'content')
    op.drop_column('messages', 'role')
    op.drop_column('messages', 'token_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('role', postgresql.ENUM('user', 'assistant', name='messagerole'), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'assistant_response')
    op.drop_column('messages', 'user_query')
    # ### end Alembic commands ###
