"""update conversation, make summary optional

Revision ID: d63c4e01939d
Revises: 705db0040a0d
Create Date: 2026-05-23 16:16:30.066674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63c4e01939d'
down_revision: Union[str, Sequence[str], None] = '705db0040a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'summary',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'summary',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
